version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=111111
      - MYSQL_DATABASE=crawl-fb
    volumes:
    - db:/var/lib/mysql
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    depends_on:
      - db
    environment:
      - DB_PASSWORD=111111
      - DB_DATABASE=crawl-fb
      - DB_HOST=db
      - NODE_OPTIONS=--max-old-space-size=4096  
    ports:
      - '9000:9000'
volumes:
  db:
    driver: local
