version: '3'
services:
  # db:
  #   image: mysql:latest
  #   container_name: mysql
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=111111
  #     - MYSQL_DATABASE=crawl-fb
  #   volumes:
  #   - ../mysql-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    # depends_on:
    #   - db
    environment:
      - DB_TYPE=mysql
      - DB_HOST=91.99.31.157
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_PASSWORD=HoangChuong@1111
      - DB_DATABASE=crawl-fb
      - NODE_OPTIONS=--max-old-space-size=4096  
    ports:
      - '9000:9000'
  facebook-sync:
    build:
      context: ./../facebook-sync
      dockerfile: Dockerfile
    container_name: facebook-sync
    restart: always
    environment:
      - DB_TYPE=mysql
      - DB_HOST=91.99.31.157
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_PASSWORD=HoangChuong@1111
      - DB_DATABASE=crawl-fb
      - NODE_OPTIONS=--max-old-space-size=4096  
    ports:
      - '7000:7000'
